baseURL: "https://shshnk94.github.io" 
title: Shashanka Subrahmanya
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

params:
    description: "Shashanka's personal webpage"
    author: Shashanka Subrahmanya
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shashanka Subrahmanya
          imageUrl: "/images/bio.jpeg"
          imageWidth: 130
          imageHeight: 130
          buttons:
            - name: Publications
              url: publications/
            - name: Jñānakosha
              url: jnanakosha/

    socialIcons:
        - name: "cv"
          url: /cv.pdf
        - name: "googlescholar"
          url: https://scholar.google.com/citations?user=mnnypPwAAAAJ
        - name: "github"
          url: https://github.com/shshnk94
        - name: "twitter"
          url: https://x.com/digitalyonko
        - name: "linkedin"
          url: https://www.linkedin.com/in/shashanka-subrahmanya/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Shashanka Subrahmanya"

titleCaseStyle: 'none'
enableGitInfo: true

caches:
  images:
    dir: :cacheDir/images

markup:
  goldmark:
    renderer:
      unsafe: true